import { HouseholdConfig, HouseholdMember, ActivityLog, DailyUsageLog, ChallengeItem } from '../types';

export const DEMO_HOUSEHOLD: HouseholdConfig = {
  id: 'demo-household-01',
  userId: 'demo-user-priya',
  name: "Priya's Eco Household",
  memberCount: 4,
  dailyTargetLitres: 400,
  hasRO: true,
  reusesROReject: false,
  hasGarden: true,
  waterSource: 'Municipal',
  bathHabit: 'Mixed',
};

export const DEMO_MEMBERS: HouseholdMember[] = [
  { id: 'm1', userId: 'demo-user-priya', name: 'Priya', role: 'Adult', color: '#0284c7' },
  { id: 'm2', userId: 'demo-user-priya', name: 'Rahul', role: 'Adult', color: '#0d9488' },
  { id: 'm3', userId: 'demo-user-priya', name: 'Ananya', role: 'Child', color: '#8b5cf6' },
  { id: 'm4', userId: 'demo-user-priya', name: 'Kabir', role: 'Child', color: '#f59e0b' },
];

export const DEMO_DAILY_LOGS: DailyUsageLog[] = [
  { id: 'd1', userId: 'demo-user-priya', date: '2026-09-01', totalLitres: 320, createdAt: '2026-09-01T20:00:00Z' },
  { id: 'd2', userId: 'demo-user-priya', date: '2026-09-02', totalLitres: 290, createdAt: '2026-09-02T20:00:00Z' },
  { id: 'd3', userId: 'demo-user-priya', date: '2026-09-03', totalLitres: 420, createdAt: '2026-09-03T20:00:00Z' },
  { id: 'd4', userId: 'demo-user-priya', date: '2026-09-04', totalLitres: 310, createdAt: '2026-09-04T20:00:00Z' },
  { id: 'd5', userId: 'demo-user-priya', date: '2026-09-05', totalLitres: 380, createdAt: '2026-09-05T20:00:00Z' },
  { id: 'd6', userId: 'demo-user-priya', date: '2026-09-06', totalLitres: 330, createdAt: '2026-09-06T20:00:00Z' },
  { id: 'd7', userId: 'demo-user-priya', date: '2026-09-07', totalLitres: 428, createdAt: '2026-09-07T20:00:00Z' },
];

export const DEMO_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    userId: 'demo-user-priya',
    activityId: 'shower',
    activityName: 'Morning Shower',
    category: 'Bathing',
    litres: 85,
    memberId: 'm1',
    memberName: 'Priya',
    date: '2026-09-07',
    notes: 'Quick refreshing shower',
    createdAt: '2026-09-07T07:30:00Z',
  },
  {
    id: 'act-2',
    userId: 'demo-user-priya',
    activityId: 'bucket_bath',
    activityName: 'Bucket Bath',
    category: 'Bathing',
    litres: 34,
    memberId: 'm2',
    memberName: 'Rahul',
    date: '2026-09-07',
    notes: 'Used standard bucket',
    createdAt: '2026-09-07T07:45:00Z',
  },
  {
    id: 'act-3',
    userId: 'demo-user-priya',
    activityId: 'brushing_teeth',
    activityName: 'Brushing & Basin',
    category: 'Bathing',
    litres: 30,
    memberId: 'm3',
    memberName: 'Ananya & Kabir',
    date: '2026-09-07',
    notes: 'Morning routine',
    createdAt: '2026-09-07T08:00:00Z',
  },
  {
    id: 'act-4',
    userId: 'demo-user-priya',
    activityId: 'laundry',
    activityName: 'Fabric Wash Cycle',
    category: 'Laundry',
    litres: 107,
    memberId: 'm1',
    memberName: 'Priya',
    date: '2026-09-07',
    notes: 'Heavy bedding wash',
    createdAt: '2026-09-07T09:30:00Z',
  },
  {
    id: 'act-5',
    userId: 'demo-user-priya',
    activityId: 'garden',
    activityName: 'Garden Watering with Hose',
    category: 'Gardening',
    litres: 94,
    memberId: 'm2',
    memberName: 'Rahul',
    date: '2026-09-07',
    notes: 'Midday balcony & lawn watering',
    createdAt: '2026-09-07T11:00:00Z',
  },
  {
    id: 'act-6',
    userId: 'demo-user-priya',
    activityId: 'dishwashing',
    activityName: 'Kitchen Cleanup & Dishes',
    category: 'Kitchen',
    litres: 48,
    memberId: 'm1',
    memberName: 'Priya',
    date: '2026-09-07',
    notes: 'Lunch cookware and plates',
    createdAt: '2026-09-07T13:30:00Z',
  },
  {
    id: 'act-7',
    userId: 'demo-user-priya',
    activityId: 'ro_purifier',
    activityName: 'RO Drinking Filter',
    category: 'Kitchen',
    litres: 30,
    memberId: 'm1',
    memberName: 'Priya',
    date: '2026-09-07',
    notes: 'Water bottle refills',
    createdAt: '2026-09-07T15:00:00Z',
  },
];

export const DEMO_CHALLENGES: ChallengeItem[] = [
  {
    id: 'c1',
    title: 'Weekly 10% Reduction',
    description: 'Save 10% compared with last week by tuning shower times and laundry batches.',
    targetSavingLitres: 280,
    currentSavingLitres: 210,
    period: 'This Week',
    isCompleted: false,
    badge: 'Water Saver',
  },
  {
    id: 'c2',
    title: '7-Day Bucket Bath Saver',
    description: 'Substitute overhead shower with bucket baths for 7 consecutive days.',
    targetSavingLitres: 200,
    currentSavingLitres: 200,
    period: 'Completed',
    isCompleted: true,
    badge: '7-Day Saver',
  },
  {
    id: 'c3',
    title: '1,000 Litres Saved Milestone',
    description: 'Reach a cumulative 1,000 litres saved across all household water activities.',
    targetSavingLitres: 1000,
    currentSavingLitres: 720,
    period: 'Ongoing',
    isCompleted: false,
    badge: '1000 L Saved',
  },
  {
    id: 'c4',
    title: 'Zero Overflow & Leak Watcher',
    description: 'Maintain zero tank overflow incidents and check taps for drips.',
    targetSavingLitres: 150,
    currentSavingLitres: 150,
    period: 'Completed',
    isCompleted: true,
    badge: 'Leak Watcher',
  },
];
